services:
  postgres:
    command: |
      -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:16.8
    network_mode: host
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pgsql-server.pem:/var/lib/postgresql/server.crt:ro
      - ./pgsql-server.key:/var/lib/postgresql/server.key:ro
version: "3.8"
volumes:
  postgres:
