- become: true
  become_user: root
  hosts: microk8sservers
  tasks:
    - lineinfile:
        create: true
        line: '{{ hostvars[item][''vars''][''advertise_ip''] }} {{ hostvars[item][''ansible_facts''][''hostname''] }} #microk8s'
        path: /etc/hosts
        regexp: '.*{{ item }} #microk8s$'
        state: present
      loop: '{{ groups[''microk8sservers''] | flatten(levels=1) }}'
      name: Generate /etc/hosts for microk8s
      when: vars['vars']['advertise_ip'] is defined
    - community.general.snap:
        channel: 1.27
        classic: true
        name:
          - microk8s
      name: Install microk8s
    - loop:
        - file: microk8s-config.yaml
          mode: "644"
      name: Template microk8s config
      template:
        dest: '{{ ansible_user_dir }}/{{ item.file }}'
        force: true
        mode: '{{ item.mode }}'
        src: ./microk8s/{{ item.file }}.j2
- become: true
  become_user: root
  hosts: microk8sprimary
  tasks:
    - name: Restart microk8s with new config
      shell: snap set microk8s config="$(cat {{ ansible_user_dir }}/microk8s-config.yaml)"
    - name: Wait
      shell: sleep 60 && microk8s status --wait-ready
    - name: Refresh certs
      shell: microk8s refresh-certs -e server.crt
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - name: Wait
      shell: sleep 60 && microk8s status --wait-ready
    - name: Get instructions to add node
      register: JOINCMD
      shell: microk8s add-node | grep {{ vars['vars']['advertise_ip'] }} | head -n1
    - debug:
        msg: '{{ JOINCMD.stdout }}'
    - shell: exit 1
      when: (JOINCMD.stdout | length) < 1
- become: true
  become_user: root
  hosts: microk8sservers
  tasks:
    - name: Restart microk8s with new config
      shell: snap set microk8s config="$(cat {{ ansible_user_dir }}/microk8s-config.yaml)"
      when:
        - inventory_hostname not in groups['microk8sprimary']
    - name: Wait
      shell: sleep 60 && microk8s status --wait-ready
      when:
        - inventory_hostname not in groups['microk8sprimary']
    - name: Refresh certs
      shell: microk8s refresh-certs -e server.crt
      when:
        - inventory_hostname not in groups['microk8sprimary']
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - name: Wait
      shell: sleep 60 && microk8s status --wait-ready
      when:
        - inventory_hostname not in groups['microk8sprimary']
- become: true
  become_user: root
  hosts: microk8sprimary
  tasks:
    - name: Extract kubeconfig
      shell: microk8s config > /var/tmp/kubeconfig.yaml
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - fetch:
        dest: ./tmp/kubeconfig.yaml
        flat: true
        src: /var/tmp/kubeconfig.yaml
      name: Fetch kubeconfig
      when:
        - lookup('ansible.builtin.fileglob', './tmp/kubeconfig.yaml') == []
    - loop:
        - name: dns
      name: Enable microk8s addons
      # - { name: community }
      # - { name: metrics-server } # will be replaced when argocd starts
      # - { name: cert-manager } # will be replaced when argocd starts
      # - { name: traefik } # microk8s installs deplyoment, but we want daemonset, will be replaced when argocd starts
      # - { name: istio } # will be replaced when argocd starts
      # - { name: knative } # will be replaced when argocd starts
      # - { name: openfaas } # will be replaced when argocd starts

      shell: microk8s enable {{ item.name }}
