- become: true
  become_user: root
  hosts: microk8sservers
  tasks:
    # - name: Run commands on others
    #   shell: if which microk8s ; then microk8s {{ item.param }} ; fi
    #   when: inventory_hostname not in groups['microk8sprimary']
    #   loop:
    #     - { param: leave }
    #     - { param: reset }
    #     - { param: stop }
    # - name: Run commands on primary
    #   shell: if which microk8s ; then microk8s {{ item.param }} ; fi
    #   loop:
    #     - { param: leave }
    #     - { param: reset }
    #     - { param: stop }
    - community.general.snap:
        name:
          - microk8s
        state: absent
      name: Remove microk8s
