- become: false
  hosts: mac
  tasks:
    - copy:
        dest: /Users/{{ ansible_user }}/multipass/
        directory_mode: "700"
        force: true
        mode: "644"
        src: ./multipass/
      name: Copy multipass scripts
  # # Doesn't work, have to ssh into mac
  # - name: Start multipass
  #   shell:
  #     chdir: '/Users/{{ ansible_user }}/multipass'
  #     cmd: 'bash run-vm1.sh up'
