concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          show-progress: false
      - name: Test with shellcheck
        run: |
          bash -ex .github/shellcheck.sh
    timeout-minutes: 10
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          show-progress: false
      - name: Apply shfmt and find unformatted files
        run: |
          bash -ex .github/shfmt.sh
    timeout-minutes: 10
name: shell-checks
on:
  pull_request:
    paths:
      - .github/shellcheck.sh
      - .github/shfmt.sh
      - .github/workflows/shell-checks.yml
      - '**.sh'
